version: '3.4'

services:
  sqlserver:
    container_name: test
    environment:
      SA_PASSWORD: "SecureP@ssw0rd1234"
    ports:
      - "1433:1433"

  api:
    image: ""
    build:
        context: .
        dockerfile: src/Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=test;Database=alpha;User Id=sa;Password=SecureP@ssw0rd1234;Encrypt=true;TrustServerCertificate=true;"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
