version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${SQL_DB_CONTAINER}  # Dynamically set the container name
    environment:
      SA_PASSWORD: "${SQL_DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ${SQL_DATA_PATH}:/var/opt/mssql
    networks:
      - app-network
    restart: on-failure:1  # Restart on failure

  api:
    image: ${DOCKER_REGISTRY}:${WEB_TAG}
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: ${API_CONTAINER}
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ConnectionStrings__DefaultConnection: "Server=${SQL_DB_CONTAINER};Database=${SQL_DB_NAME};User Id=sa;Password=${SQL_DB_PASSWORD};Encrypt=true;TrustServerCertificate=true;"
    ports:
      - "${API_PORT}:80"  # Map HTTP port
      - "8081:443" # Map HTTPS port (change to your desired port if necessary)
    volumes:
      - ${FILE_STORE_PATH}:/app/filestores
    depends_on:
      - sqlserver
    networks:
      - app-network
    restart: on-failure:3  # Restart on failure

networks:
  app-network:
    driver: bridge