name: CICD

on: 
  push:
    branches:
      - dev
      - staging
      - main
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

permissions:
  id-token: write
  contents: read

jobs:
  set-environment-name:
    runs-on: ubuntu-latest
    outputs:
      environmentName: ${{ steps.set-env-name.outputs.environmentName }}
    steps:
      - name: Set environmentName
        id: set-env-name
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            ENV_NAME="production"
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            ENV_NAME="staging"
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            ENV_NAME="development"
          fi
          echo "ENV_NAME=${ENV_NAME}"
          echo "environmentName=${ENV_NAME}" >> $GITHUB_OUTPUT

  build:
    needs: [set-environment-name]
    uses: ./.github/workflows/build.yml
    with:
      environmentName: ${{ needs.set-environment-name.outputs.environmentName }}
      build-artifacts: true

  # deploy-development:
    # if: github.ref == 'refs/heads/dev'
    # uses: ./.github/workflows/deploy-self-hosted.yml
    # secrets: inherit
    # needs: [ build ]
    # with:
      # environmentName: Development

  # deploy-staging:
    # if: github.ref == 'refs/heads/staging'
    # uses: ./.github/workflows/deploy-self-hosted.yml
    # secrets: inherit
    # needs: [ build ]
    # with:
      # environmentName: Staging

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: [build]
    uses: ./.github/workflows/deploy-self-hosted.yml
    secrets: inherit
    with:
      environmentName: production
      webTag: ${{ needs.build.outputs.webTag }}  # Pass the web_tag output from the build job
