name: CICD

on: 
  push:
    branches:
      - dev
      - staging
      - main
    paths-ignore:
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - README.md

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with:
      build-artifacts: true

  # deploy-development:
    # if: github.ref == 'refs/heads/dev'
    # uses: ./.github/workflows/deploy-self-hosted.yml
    # secrets: inherit
    # needs: [ build ]
    # with:
      # environmentName: Development

  # deploy-staging:
    # if: github.ref == 'refs/heads/staging'
    # uses: ./.github/workflows/deploy-self-hosted.yml
    # secrets: inherit
    # needs: [ build ]
    # with:
      # environmentName: Staging

  deploy-production:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-self-hosted.yml
    secrets: inherit
    needs: [ build ]
    with:
      environmentName: Production
